#Jegotrip
DOMAIN-SUFFIX,jegotrip.cn
DOMAIN-SUFFIX,jegotrip.com.cn
DOMAIN-SUFFIX,jegotrip.com
DOMAIN-SUFFIX,umeng.com
IP-CIDR,54.222.246.1/32,no-resolve
IP-CIDR,54.222.242.252/32,no-resolve
IP-CIDR,18.162.71.27/32,no-resolve
IP-CIDR,18.163.199.29/32,no-resolve
IP-CIDR,18.167.45.112/32,no-resolve
IP-CIDR,16.162.59.136/32,no-resolve
IP-CIDR,184.169.245.128/32,no-resolve
IP-CIDR,18.163.90.101/32,no-resolve
